name: CI

on:
  workflow_dispatch:
  push

jobs:
  test:
    name: Build, test, poly check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: 1.10.3.933
      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.polylith
            ~/.m2
            ~/.gitlibs
            ~/.clojure
          key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-
      - name: Force clojure to resolve dependencies
        run: clojure -M:dev:test
      - name: Check Polylith workspace
        run: clojure -M:poly check
      - name: Run tests for polylith workspace
        if: success()
        run: clojure -M:poly test